# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
site_name: News from Loop and Learn

theme:
    name: material
    language: en
    features:
        - navigation.footer
        - navigation.tabs
        - navigation.tabs.sticky
        - navigation.tracking
        - navigation.top
        - search.suggest
        - search.highlight
        - content.code.annotate
        - content.tooltips
    logo: lnl-newsletter-logo.png
    favicon: lnl-newsletter-logo.png
    palette:
        # Palette toggle for light mode
        - media: "(prefers-color-scheme: light)"
          scheme: default
          primary: custom
          toggle:
            icon: material/brightness-7
            name: Switch to dark mode

        # Palette toggle for dark mode
        - media: "(prefers-color-scheme: dark)"
          scheme: slate
          primary: custom
          toggle:
            icon: material/brightness-4
            name: Switch to light mode

# repo_url: https://github.com/LoopKit/Loop

extra_css:
    - stylesheets/extra.css
    - stylesheets/primary-color.css

markdown_extensions:
    - meta
    - abbr
    - admonition
    - attr_list
    - pymdownx.arithmatex:
          generic: true
    - pymdownx.details
    - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji 
        emoji_generator: !!python/name:materialx.emoji.to_svg
    - pymdownx.highlight
    - pymdownx.mark
    - pymdownx.tilde
    - pymdownx.inlinehilite
    - pymdownx.keys
    - pymdownx.superfences:
        # make exceptions to highlighting of code:
        custom_fences:
          - name:  mermaid
            class: mermaid
            format: !!python/name:pymdownx.superfences.fence_code_format
    - pymdownx.snippets:
        auto_append:
            - includes/tooltip-list.txt
    - toc:
        permalink: true
        permalink_title: Anchor link to this Header on this Page
        toc_depth: 3
        title: Headers on this Page
extra_javascript:
    - https://polyfill.io/v3/polyfill.min.js?features=es6
    - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

plugins:
    - search
    - htmlproofer:
        enabled: !ENV [CHECK_BROKEN_LINKS, False]
        raise_error_after_finish: true
    - unused_files:
        enabled: !ENV [CHECK_UNUSED_FILES, False]
        excluded_files:
            - .DS_Store
            - build/.DS_Store            
            - gh-actions/.DS_Store
            - gh-actions/img/.DS_Store
            - loop-logo.png
            - stylesheets/extra.css
            - stylesheets/primary-color.css

use_directory_urls: !ENV [CHECK_BROKEN_LINKS, True]

nav:
- Current: 'index.md'
- Edition by Date:
    - '2024-01-11': 'edition/2024-01-11.md'
    - '2024-01-02': 'edition/2024-01-02.md'
    - '2023':
      - '2023 December':
        - '2023-12-24': 'edition/2023-12-24.md'
        - '2023-12-18': 'edition/2023-12-18.md'
        - '2023-12-11': 'edition/2023-12-11.md'
        - '2023-12-04': 'edition/2023-12-04.md'
      - '2023 November':
        - '2023-11-26': 'edition/2023-11-26.md'
        - '2023-11-19': 'edition/2023-11-19.md'
        - '2023-11-12': 'edition/2023-11-12.md'
        - '2023-11-06': 'edition/2023-11-06.md'
      - '2023 October':
        - '2023-10-30': 'edition/2023-10-30.md'
        - '2023-10-22': 'edition/2023-10-22.md'
        - '2023-10-15': 'edition/2023-10-15.md'
        - '2023-10-08': 'edition/2023-10-08.md'
        - '2023-10-01': 'edition/2023-10-01.md'
      - '2023 September':
        - '2023-09-24': 'edition/2023-09-24.md'
        - '2023-09-17': 'edition/2023-09-17.md'
        - '2023-09-11': 'edition/2023-09-11.md'
- Translation: 'translate.md'
