# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
site_name: LnL Newseltter

theme:
    name: material
    language: en
    features:
        - navigation.footer
        - navigation.tabs
        - navigation.tabs.sticky
        - navigation.tracking
        - navigation.top
        - search.suggest
        - search.highlight
        - content.code.annotate
        - content.tooltips
    logo: lnl-icon.png
    favicon: lnl-icon.png
    palette:
        # Palette toggle for light mode
        - media: "(prefers-color-scheme: light)"
          scheme: default
          primary: custom
          toggle:
            icon: material/brightness-7
            name: Switch to dark mode

        # Palette toggle for dark mode
        - media: "(prefers-color-scheme: dark)"
          scheme: slate
          primary: custom
          toggle:
            icon: material/brightness-4
            name: Switch to light mode

# repo_url: https://github.com/LoopKit/Loop

extra_css:
    - stylesheets/extra.css
    - stylesheets/primary-color.css

markdown_extensions:
    - meta
    - abbr
    - admonition
    - attr_list
    - pymdownx.arithmatex:
          generic: true
    - pymdownx.details
    - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji 
        emoji_generator: !!python/name:materialx.emoji.to_svg
    - pymdownx.highlight
    - pymdownx.mark
    - pymdownx.tilde
    - pymdownx.inlinehilite
    - pymdownx.keys
    - pymdownx.superfences:
        # make exceptions to highlighting of code:
        custom_fences:
          - name:  mermaid
            class: mermaid
            format: !!python/name:pymdownx.superfences.fence_code_format
    - pymdownx.snippets:
        auto_append:
            - includes/tooltip-list.txt
    - toc:
        permalink: true
        permalink_title: Anchor link to this Header on this Page
        toc_depth: 3
        title: Headers on this Page
extra_javascript:
    - https://polyfill.io/v3/polyfill.min.js?features=es6
    - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

plugins:
    - search
    - htmlproofer:
        enabled: !ENV [CHECK_BROKEN_LINKS, False]
        raise_error_after_finish: true
    - unused_files:
        enabled: !ENV [CHECK_UNUSED_FILES, False]
        excluded_files:
            - .DS_Store
            - build/.DS_Store            
            - gh-actions/.DS_Store
            - gh-actions/img/.DS_Store
            - loop-logo.png
            - stylesheets/extra.css
            - stylesheets/primary-color.css

use_directory_urls: !ENV [CHECK_BROKEN_LINKS, True]

nav:
- Home: 'index.md'
- Back Issues:
    - '2023 09 17': 'old/20230917.md'
- Translation: 'translate.md'
